### ISSUE TITLE
Interrupt Handler

### ISSUE THREAD

**Issue by EvilWays1** [I-Spangler/TIS-100-solutions#1]
Your solution for this puzzle doesn't work. The right most box in the middle row needs to be the following:

MOV UP, ACC
SUB UP
JLZ Y
MOV LEFT, **DOWN**
JMP END
Y: MOV 4, **DOWN**
MOV LEFT, NIL
END: MOV 0, ACC

**Comment by istrangeloop** [comment]
Fixed

Em 21 de out de 2017 01:17, "EvilWays1" <notifications@github.com> escreveu:
